### PR TITLE
DOCKER-295 Add support for relaxedQueryChars

### PR DESCRIPTION
**Pull request by rschev**
This should be tested with Alfresco images as well.

### CODE REVIEW

**Comment by tgeens** [comment]
Can you add that to the README.md ?

**Comment by tgeens** [comment]
And shouldn't we add `relaxedPathChars` in the same effort ?

**Comment by rschev** [comment]
@tgeens I've updated the README. I'm less certain about whether `relaxedPathChars` is needed, whereas I have a concrete interoperability case for `relaxedQueryChars`

**Comment by rschev** [comment]
@tgeens I've added support for `relaxedPathChars`.

**Review by tgeens — APPROVED** [review]

**Pull request merged**
