### PR TITLE
Base all JDK-8 ubuntu images on bionic (18.04 LTS)

### PR DESCRIPTION
**Pull request by tgeens**

### CODE REVIEW

**Review by rschev — APPROVED** [review]

**Comment by rschev** [comment]
I think the readme still needs to be updated.

**Comment by rschev** [comment]
@tgeens Can you verify that my readme update didn't change too much?

**Comment by tgeens** [comment]
Cleaned up the tags in the readme some more

(and fixed up the gradle task to print the tags -> `./gradlew printTags`)

**Comment by tgeens** [comment]
Hmm, do integration tests even run in Travis ?

**Comment by anghelutar** [comment]
> Hmm, do integration tests even run in Travis ?

Yes, travis file runs './gradlew check --info' - see:
https://github.com/xenit-eu/docker-tomcat/blob/master/.travis.yml

And on travis output:

.....
eu.xenit.docker.tomcat.JdkTests > testJdkVersion STANDARD_OUT
    Request method:	GET
    Request URI:	http://127.0.0.1:32768/
    HTTP/1.1 200 OK
eu.xenit.docker.tomcat.RemoteIpValveTests > testRemoteIpValve STANDARD_OUT
    Request method:	GET
    Request URI:	http://127.0.0.1:32768/
    Headers:		Host=alf1hubspot.dev.xenit.eu
    				X-Forwarded-For=81.82.199.31
    				X-Forwarded-Proto=https
    				Accept=*/*
    HTTP/1.1 200 OK
eu.xenit.docker.tomcat.RemoteIpValveTests > testDefaultIndex STANDARD_OUT

**Comment by tgeens** [comment]
Cool, thank you!

**Pull request merged**
